apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sum-service
  template:
    metadata:
      labels:
        app: sum-service
    spec:
      containers:
      - name: sum-service
        image: ghcr.io/sonsai/my-sum-service:latest
        ports:
        - containerPort: 80
